### ISSUE TITLE
[FEATURE] Add hovering effects on Links

### ISSUE THREAD

**Issue by nathgoutam93** [nathgoutam93/linkgen-react#2]
### Description

The Links has no hovering effects nor transitions, it would be better to have some .

Like scaling the link size by 1.1 scale. And adding transition for it.

**Comment by APOORVANAGAR-2002** [comment]
Hi
Can I work on this issue?

**Comment by nathgoutam93** [comment]
> Hi Can I work on this issue?

Sure go ahead

**Comment by Parzivalcen** [comment]
Would you assign this to me ?

**Comment by nathgoutam93** [comment]
@Parzivalcen I have to confirm if other assignee is not working on it anymore before assigning someone else.

Hey there, @APOORVANAGAR-2002  are you working on it

**Comment by APOORVANAGAR-2002** [comment]
Yes, actually got stuck in rectifying the conflict between prettier and eslint
Will complete it by today.

**Comment by nathgoutam93** [comment]
> Yes, actually got stuck in rectifying the conflict between prettier and eslint Will complete it by today.

  great . Feel free to ask if you need any help?

**Comment by APOORVANAGAR-2002** [comment]
https://user-images.githubusercontent.com/60841039/155718748-d1e3f959-45e8-4fd7-a743-8bae682dd7a9.mp4

@nathgoutam93 Is it something that you were looking for?

**Comment by nathgoutam93** [comment]
> 69dc49ff-6f15-44cf-9f22-b20e8602dd10.mp4 
> @nathgoutam93 Is it something that you were looking for?

Yes , it would work . Also please try to add the the hovering code inside the code.js as the generated code  gets the CSS from useCode hook

**Comment by nathgoutam93** [comment]
Oh also I have added new option to add social links as icon you can add this same scaling effect to those as well . Just do fetch and merge to get those latest changes to work on @APOORVANAGAR-2002

**Comment by APOORVANAGAR-2002** [comment]
> > 69dc49ff-6f15-44cf-9f22-b20e8602dd10.mp4
> > @nathgoutam93 Is it something that you were looking for?
> 
> Yes , it would work . Also please try to add the the hovering code inside the code.js as the generated code gets the CSS from useCode hook

Sorry, didn't get it

**Comment by APOORVANAGAR-2002** [comment]
> Oh also I have added new option to add social links as icon you can add this same scaling effect to those as well . Just do fetch and merge to get those latest changes to work on @APOORVANAGAR-2002

ok

**Comment by nathgoutam93** [comment]
> > > 69dc49ff-6f15-44cf-9f22-b20e8602dd10.mp4
> > > @nathgoutam93 Is it something that you were looking for?
> > 
> > 
> > Yes , it would work . Also please try to add the the hovering code inside the code.js as the generated code gets the CSS from useCode hook
> 
> Sorry, didn't get it

https://github.com/nathgoutam93/linkgen-react/blob/master/src/hooks/code.js 

In this hook you will see some CSS classes inside the style tag, you will find a class for the link element as well with "link-container" just add the transition properties to the CSS.

If you find it confusing you can skip it.

**Comment by APOORVANAGAR-2002** [comment]
@nathgoutam93 Really sorry!
I won't be able to do it, currently stuck with some work. Sorry for the delay

**Comment by nathgoutam93** [comment]
> @nathgoutam93 Really sorry! I won't be able to do it, currently stuck with some work. Sorry for the delay

Okay no problem I'll assign it to someone else

**Comment by Ash-KODES** [comment]
can I work on this?

**Comment by nathgoutam93** [comment]
> can I work on this?

Sure go ahead

**Comment by nathgoutam93** [comment]
@Ash-KODES hey there are you working on this? 

If you need any help please let me know
